import React from "react";
import { Sparkles, Calendar, Clock, ChevronRight, CheckCircle, Code2, AlertCircle } from "lucide-react";

export function WeeklyPlanView({
  plan,
  onGenerateNewPlan,
  isGenerating,
  generationProgress = 0,
  generationMessage = "",
  onOpenQuestionDrawer
}) {
  if (!plan) return null;

  return (
    <div className="runway-container">
      {/* Runway Header Deck */}
      <div className="runway-header-deck">
        <div className="runway-title-box">
          <div className="runway-title">
            7-Day Revision Runway
          </div>
          <div className="runway-subtitle">
            Autonomous study trajectory generated by Twin. Weighted 70% toward critical weakness drills.
          </div>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
          {isGenerating ? (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: "0.25rem" }}>
              <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.8rem", color: "var(--accent-cyan)" }}>
                {generationMessage || "Synthesizing revision runway..."} ({Math.round(generationProgress * 100)}%)
              </div>
              <div style={{ width: "200px", height: "4px", background: "var(--bg-deck)", borderRadius: "2px", overflow: "hidden" }}>
                <div
                  style={{
                    width: `${Math.round(generationProgress * 100)}%`,
                    height: "100%",
                    background: "var(--accent-cyan)",
                    transition: "width 0.3s ease"
                  }}
                />
              </div>
            </div>
          ) : (
            <button
              type="button"
              className="action-btn-primary"
              onClick={onGenerateNewPlan}
              disabled={isGenerating}
            >
              <Sparkles size={16} />
              Re-Synthesize Plan
            </button>
          )}
        </div>
      </div>

      {/* 7-Day Runway Cards Grid */}
      <div className="runway-days-grid">
        {plan.daily_sessions?.map((session) => {
          let dayClass = "review-day";
          if (session.urgency === "CRITICAL") dayClass = "critical-day";
          else if (session.urgency === "STABLE" || session.urgency === "MASTERED") dayClass = "stable-day";

          return (
            <div key={session.day_number} className={`day-card ${dayClass}`}>
              <div>
                <div className="day-card-header">
                  <div>
                    <span className="day-number-tag">
                      DAY 0{session.day_number} // {session.date}
                    </span>
                    <h3 className="day-focus-topic">{session.focus_topic}</h3>
                  </div>
                  <span className={`urgency-badge urgency-${session.urgency.toLowerCase()}`}>
                    {session.session_type}
                  </span>
                </div>

                <div style={{ marginTop: "0.75rem" }}>
                  <p className="day-objective-text">{session.target_objective}</p>
                </div>
              </div>

              <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
                <div className="day-meta-row">
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "0.3rem" }}>
                    <Clock size={13} color="var(--accent-cyan)" />
                    {session.allocated_minutes} Minutes
                  </span>
                  <span>•</span>
                  <span>{session.questions?.length || 0} LeetCode Java Problems</span>
                </div>

                {session.questions && session.questions.length > 0 && (
                  <div className="day-questions-list">
                    {session.questions.map((q) => (
                      <div
                        key={q.id}
                        className="question-preview-pill"
                        onClick={() => onOpenQuestionDrawer(q, session)}
                        title="Click to open coding question details"
                      >
                        <span style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
                          <Code2 size={13} color="var(--accent-cyan)" />
                          <span style={{ fontWeight: 500, color: "var(--text-pure)" }}>{q.title}</span>
                        </span>
                        <span style={{
                          fontFamily: "var(--font-mono)",
                          fontSize: "0.7rem",
                          color: q.difficulty === "Easy" ? "var(--accent-emerald)" : q.difficulty === "Hard" ? "var(--accent-rose)" : "var(--accent-amber)"
                        }}>
                          {q.difficulty}
                        </span>
                      </div>
                    ))}
                  </div>
                )}

                <button
                  type="button"
                  className="open-drawer-btn"
                  onClick={() => onOpenQuestionDrawer(session.questions?.[0] || null, session)}
                >
                  <span>Open Practice Drawer</span>
                  <ChevronRight size={14} />
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
